travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,8 +3,8 @@ python:
   - "3.6.3"
 services:
   - docker
-#before_install:
-# - set -e
+before_install:
+ - set -e
 
 notifications:
   slack:
@@ -12,7 +12,7 @@ notifications:
     on_failure: change
 
 env:
- - RELEASE=docker_update PRONLEX=sttsse/pronlex MARYTTS=sttsse/marytts IMAGETAG=wikispeech_mockup_travis
+ - RELEASE=affff
 
 # https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
 # sudo: required
@@ -20,45 +20,31 @@ env:
 # group: deprecated-2017Q4
  
 install:
- - set -e
  - sudo apt install opus-tools
  - pip install -r requirements.txt
 
 # command to run tests
 script:
- - set +e
  - | # build pronlex from $RELEASE if it exists, otherwise master
    echo "pronlex building from $RELEASE"
-   docker build https://github.com/stts-se/pronlex.git#$RELEASE -t $PRONLEX:$IMAGETAG --build-arg RELEASE=$RELEASE
-   if [ $? -eq 0 ]; then
-     echo "pronlex built from $RELEASE"
-   else
-     set -e
-     echo "pronlex building from master"
-     docker build https://github.com/stts-se/pronlex.git -t $PRONLEX:$IMAGETAG --build-arg RELEASE=$RELEASE
-     echo "pronlex built from master"
-     set +e
-   fi
- - set +e
+   git clone https://github.com/stts-se/pronlex.git
+   cd pronlex
+   git checkout $RELEASE || echo "$RELEASE not found, fallback to master"
+   cd ..
+   docker build pronlex -t pronlex --build-arg RELEASE=$RELEASE
  - | # build marytts from $RELEASE if it exists, otherwise master
    echo "marytts building from $RELEASE"
-   docker build https://github.com/stts-se/marytts.git#$RELEASE -t $MARYTTS:$IMAGETAG --build-arg RELEASE=$RELEASE
-   if [ $? -eq 0 ]; then
-     echo "marytts built from $RELEASE"
-   else
-     set -e
-     echo "marytts building from master"
-     docker build https://github.com/stts-se/marytts.git -t $MARYTTS:$IMAGETAG --build-arg RELEASE=$RELEASE
-     echo "marytts built from master"
-     set +e
-   fi
- - set -e
- - docker run -v /appdir:/appdir -p 8787:8787 -t $PRONLEX:$IMAGETAG /wikispeech/pronlex/bin/setup /appdir
- - docker run -v /appdir:/appdir -p 8787:8787 -t $PRONLEX:$IMAGETAG &
+   git clone https://github.com/stts-se/marytts.git
+   cd marytts
+   git checkout $RELEASE || echo "$RELEASE not found, fallback to master"
+   cd ..
+   docker build marytts -t MARYTTS:$IMAGETAG --build-arg RELEASE=$RELEASE
+ - docker run -v /appdir:/appdir -p 8787:8787 -t pronlex /wikispeech/pronlex/bin/setup /appdir
+ - docker run -v /appdir:/appdir -p 8787:8787 -t pronlex &
  - export pronlex_pid=$!
  - echo "pronlex running with pid $pronlex_pid"
  - sleep 20
- - docker run -p 59125:59125 -t $MARYTTS:$IMAGETAG &
+ - docker run -p 59125:59125 -t marytts &
  - export marytts_pid=$!
  - echo "marytts running with pid $marytts_pid"
  - sleep 20
