ws-postponed-start

diff --git a/docker/ws-postponed-start b/docker/ws-postponed-start
--- a/docker/ws-postponed-start
+++ b/docker/ws-postponed-start
@@ -30,14 +30,18 @@ for s in $*; do
 	    echo "[$CMD] Service dependency up and running: $s" 2>&1
 	    exitcode=0
 	    break
+	elif [ $res -eq 56 ]; then
+	    curl $s
+	    echo "[$CMD] Service dependency failed (error code $res): $s" 2>&1
+	    exitcode=1
+	    exit 1
+	else
+	    curl $s # repeat to get error msg		
 	fi
-	if [ $exitcode -eq 0 ]; then
-	    break
-	fi	
 	sleep 5
     done
     if [ $exitcode -eq 1 ]; then
-       echo "[$CMD] Reached timeout for service dependency: $s" 2>&1
+       echo "[$CMD] Service dependency failed: $s" 2>&1
        exit 1
     fi
 done
